version: '3.8'

services:
  # Server Web (PHP & Apache)
  web:
    image: php:8.2-apache
    container_name: pweb_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
    # Perintah untuk install ekstensi MySQL agar PHP bisa baca database
    command: >
      sh -c "docker-php-ext-install mysqli && apache2-foreground"

  # Database (MariaDB)
  db:
    image: mariadb:10.4
    container_name: pweb_db
    restart: always
    environment:
      MARIADB_DATABASE: project_pweb
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      # Otomatis import file SQL saat pertama kali dijalankan
      - ./project_pweb_rill.sql:/docker-entrypoint-initdb.d/project_pweb_rill.sql
    ports:
      - "3306:3306"